### PR TITLE
Add CSV pipelines for UK trade/total trade in services

### PR DESCRIPTION
**Pull request by samuelhwilliams**
### Description of change
Dataset 3 and 4 - https://drive.google.com/file/d/1XntCt2sMgPxgKnr_vT2eZmtQ_REBwkXf/view?ths=true

### Checklist

* [x] Has the [CHANGELOG](https://github.com/uktrade/data-flow/blob/master/CHANGELOG.md) been updated?

### CODE REVIEW

**Comment by samuelhwilliams** [comment]
Data have signed off on the shape of this for now - though some small tweaks may come along in the future. For now it would be good to get this in so we can send them the result for further checks.

**Comment by niross** [comment]
Were the two csvs supposed to be included?

**Comment by samuelhwilliams** [comment]
In this PR? No

**Comment by niross** [comment]
Yeah the csvs themselves... the addition of the files `ons_uk_total_trade_in_services.csv` and `ons_uk_trade_in_services.csv` to the repo.

Also I guess `.coverage` should be gitignored?

**Comment by samuelhwilliams** [comment]
@niross 🤦 removed.

**Pull request merged**
