### PR TITLE
json conversion of decimal objects to float

### PR DESCRIPTION
**Pull request by dvoong**
### Checklist

* [ ] Have tests been added to cover any changes?
* [ ] Has the [CHANGELOG](https://github.com/uktrade/data-flow/blob/master/CHANGELOG.md) been updated?
* [ ] Has the README been updated (if needed)?

### CODE REVIEW

**Comment by allait** [comment]
Conversion to float is lossy and potentially corrupts data. What's the problem with keeping them as Decimals?

**Comment by dvoong** [comment]
> Conversion to float is lossy and potentially corrupts data. What's the problem with keeping them as Decimals?

`json.dumps` complains it can't convert `Decimal` objects and raises an exception

**Comment by allait** [comment]
@dvoong let's convert them to strings in the query itself or (if that doesn't work) here. SQLAlchemy should then be able to handle converting it back for compatible columns.

**Comment by dvoong** [comment]
I'm going to close this pull request and created a new one with changes to the sql query

**Comment by dvoong** [comment]
https://github.com/uktrade/data-flow/pull/128

**Pull request closed without merging**
