### PR TITLE
feat: increase high memory worker concurrency

### PR DESCRIPTION
**Pull request by samuelhwilliams**
### Description of change
We've bumped the memory on the high memory worker from ~5G to 10G. We
have more tasks using this worker class now, and the memory should be
sufficient for multiple jobs, so let's also bump the concurrency.

### Checklist

* [ ] Have tests been added to cover any changes?
* [ ] Has the README been updated (if needed)?

### CODE REVIEW

**Review by niross — APPROVED** [review]

**Comment by michalc** [comment]
Should we instead have more high memory workers at 5GB rather than fewer at 10GB? Few reasons:

- With concurrency of 1, each job is unlikely to affect any other, so if something breaks, it's pretty clear it's due to the one that's breaking, and not another job that happens to be running at the same time

- Realistically, we would likely get more CPU/resources with two workers rather than one, since they could be on different physical boxes, and most PaaS clients really underuse their allocation(?)

**Comment by michalc** [comment]
I wonder also, if we should be moving to having a concurrency of 1 for all workers, and then firing them up on demand...

**Comment by samuelhwilliams** [comment]
> I wonder also, if we should be moving to having a concurrency of 1 for all workers, and then firing them up on demand...

Firing up workers on demand would definitely be nice. CloudFoundry has a `run-task` thing which allows specifying disk+memory limits, which is great. You can't SSH into task instances. This would be a pain while we still don't have access to logs in airflow during the task run. Might look into these two issues for firebreak...

As to your other points: I think valid. So will just close this off.

**Comment by michalc** [comment]
> Might look into these two issues for firebreak...

Sounds _great_

**Pull request closed without merging**
